routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', function () {

	return view('auth.login');
});

Route::group(['middleware' => 'admin'], function() {

	Route::get('/home', function () {
		$data = App\karyawan::count();
		$jml_absensi = App\absen::count();
		$jml_lembur = App\laporanlembur::count();
		$jml_lokasi = App\lokasi::count();
		return view('home', compact('data','jml_absensi','jml_lembur','jml_lokasi'));
	});

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('admin/routes', 'HomeController@admin');
Route::resource('karyawan','KaryawanController');
Route::resource('jabatan','jabatancontroller');
Route::resource('lokasi','lokasicontroller');

Route::get('laporanabsensi', 'laporanabsensicontroller@index');
Route::post('laporanabsensi/search', 'laporanabsensicontroller@search')->name('report.search');
Route::get('laporanlembur', 'laporanlemburcontroller@index');
Route::post('laporanlembur/search', 'laporanlemburcontroller@search')->name('lamporanlembur.search');
});

app/jabatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class jabatan extends Model
{
    //
    protected $table = 'jabatan';

    /**
     * @var array
     */
    protected $guarded = [];
}

app/Http/Controllers/jabatancontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\jabatan;

class jabatancontroller extends Controller
{
    //
    public function index()
    {
        //
        $jabatan = Jabatan::all();
        return view('jabatan.index', compact('jabatan'));
    }
    public function show(Jabatan $jabatan)
    {
        return $jabatan;
    }

    public function create()
    {
        return view('jabatan.create');
    }

    public function store(Request $request)
    {
        $validasi = $request->validate([
            'nama' => 'required',
           
        ]);
        $jabatan = Jabatan::create($validasi);
   
        return redirect('/jabatan')->with('success', 'Selamat data berhasil ditambah!');
    }

    public function edit(Jabatan $jabatan)
    {
        return view('jabatan.edit', compact('jabatan'));
    }

    public function update(Request $request, $id)
    {
        $validasi = $request->validate([
            'nama' => 'required'
        ]);
        Jabatan::whereId($id)->update($validasi);

        return redirect('/jabatan')->with('success', 'Data berhasil di update');
    }

    public function destroy( $id)
    {
        $jabatan = Jabatan::findOrFail($id);
        $jabatan->delete();

        return redirect('/jabatan')->with('success', 'Data berhasil dihapus!');
    }
}

resources/views/jabatan/create.blade.php
@extends ('layouts.main')

@section('layout')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Tambah Jabatan</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('jabatan.store') }}">
            @csrf
            <div class="form-group">
                <label>Nama</label>
                <input type="text" class="form-control" name="nama" />
            </div>
            <button type="submit" class="btn btn-primary">Tambah Data</button>
        </form>
    </div>
</div>
@endsection

resources/views/jabatan/edit.blade.php
@extends ('layouts.main')
@section('layout')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Ubah Jabatan</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif

        <form action="{{ route('jabatan.update',$jabatan->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="form-group">
                <label>Nama</label>
                <input type="text" class="form-control" name="nama" value="{{ $jabatan->nama }}" />
            </div>
            <button type="submit" class="btn btn-primary">Edit Data</button>
    </div>

    </form>
</div>
</div>
@endsection

resources/views/jabatan/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Presensi</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('/assets/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{('/assets/css/metisMenu.min.css')}}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{{asset('/assets/css/dataTables/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{asset('/assets/css/dataTables/dataTables.responsive.css')}}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{asset('/assets/css/startmin.css')}}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{asset('/assets/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>

<body>
    @extends('layouts.main')
    @section('layout')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Daftar Jabatan</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{{ route('jabatan.create')}}" type="button" class="btn btn-primary">Tambah Jabatan</a>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $no = 0;?>
                                    @foreach($jabatan as $data)
                                    <?php $no++ ;?>
                                    <tr>
                                        <td class="text-center">{{$no}}</td>
                                        <td>{{$data->nama}}</td>
                                        <td>
                                            <form action="{{ route('jabatan.destroy', $data->id)}}" method="POST">
                                                @csrf
                                                <input type="hidden" name="_method" value="DELETE">
                                                <a href="{{ route('jabatan.edit', $data->id)}}"
                                                    class="btn btn-warning btn-sm">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->


    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{{asset('/assets/js/jquery.min.js')}}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{asset('/assets/js/bootstrap.min.js')}}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{asset('/assets/js/metisMenu.min.js')}}"></script>

    <!-- DataTables JavaScript -->
    <script src="{{asset('/assets/js/dataTables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('/assets/js/dataTables/dataTables.bootstrap.min.js')}}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{asset('/assets/js/startmin.js')}}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });

    </script>

    @endsection

</body>

</html>