routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', function () {

	return view('auth.login');
});

Route::group(['middleware' => 'admin'], function() {

	Route::get('/home', function () {
		$data = App\karyawan::count();
		$jml_absensi = App\absen::count();
		$jml_lembur = App\laporanlembur::count();
		$jml_lokasi = App\lokasi::count();
		return view('home', compact('data','jml_absensi','jml_lembur','jml_lokasi'));
	});

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('admin/routes', 'HomeController@admin');
Route::resource('karyawan','KaryawanController');
Route::resource('jabatan','jabatancontroller');
Route::resource('lokasi','lokasicontroller');

Route::get('laporanabsensi', 'laporanabsensicontroller@index');
Route::post('laporanabsensi/search', 'laporanabsensicontroller@search')->name('report.search');
Route::get('laporanlembur', 'laporanlemburcontroller@index');
Route::post('laporanlembur/search', 'laporanlemburcontroller@search')->name('lamporanlembur.search');
});

app/karyawan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class karyawan extends Model
{
    //
    protected $table = 'karyawan';

    /**
     * @var array
     */
    protected $guarded = [];
}

app/Http/Controllers/karyawancontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\jabatan;
use App\User;
use App\karyawan;
class karyawancontroller extends Controller
{
    //
    public function index()
    {
        $dk = DB::table('karyawan')
        ->leftJoin('jabatan','karyawan.id_jabatan','=','jabatan.id')
        ->select('karyawan.*','jabatan.nama as nama_jabatan')
        ->paginate(10);
        return view('karyawan.index', compact('dk'));
    }
    public function create()
    {
        $jabatan = jabatan::orderBy('nama', 'ASC')->get();
        return view('karyawan.create',compact('jabatan'));
    }

    public function store(Request $request)
    {
        if ($request->nik == '' || $request->nama == '' || $request->password == ''){
            session()->flash('message','Tidak Boleh ada kolom kosong');
            return view('karyawan.index');
          }
      
           if (DB::table('karyawan')->where('NIK',$request->nik)->first() != null) {
           session()->flash('message','Anda Sudah Terdaftar');
           return view('dashboard.index');
           }else{
      
            DB::table('users')->insert([
              'name'=>$request->nama,
              'email'=>$request->email,
              'password'=>Hash::make($request->password)
            ]);
         
            DB::table('karyawan')->insert([
              'id_user' => User::all()->last()->id,
              'nama'=>$request->nama,
              'nik'=>$request->nik,
              'telp'=>$request->telp,
              'id_jabatan'=>$request->id_jabatan
            ]);
            
            return redirect('/karyawan')->with('success', 'Selamat data berhasil ditambah!');
          }
    }

    public function edit($id)
    {
       $karyawan = karyawan::findOrFail($id);
       $user = User::findOrFail($karyawan->id_user);
       $jabatan = jabatan::orderBy('nama', 'ASC')->get();
      return view('karyawan.edit', compact('karyawan', 'jabatan','user'));

    }

    public function update(Request $request, $id)
    {
       //validasi
    $this->validate($request, [
    
      'nama' => 'required|string|max:100',
      'nik' => 'required|integer',
      'email' => 'required',
      'telp' => 'required',
      'id_jabatan' => 'required',
    ]);
    $karyawan = karyawan::findOrFail($id);
    

    //perbaharui data di database
    $karyawan->update([
        'nama' => $request->nama,
        'nik' => $request->nik,
        'id_jabatan' => $request->id_jabatan,
    ]);

    $user = User::findOrFail($karyawan->id_user);

    $user->update([
      'email' => $request->email,
      'password' => $request->password,
      'nama' => $request->nama,
    ]);
    return redirect('/karyawan')->with('success', 'Data berhasil di update');
    }


    public function destroy($id)
    {
        $karyawan = Karyawan::findOrFail($id);
        $user = User::findOrFail($karyawan->id_user);
        $karyawan->delete();
        $user->delete();

        return redirect('/karyawan')->with('success', 'Data berhasil dihapus!');
    }
}

resources/views/karyawan/create.blade.php
@extends ('layouts.main')

@section('layout')
<div class="container-fluid">
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Tambah Karyawan</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('karyawan.store') }}">
            @csrf
            <div class="form-group">
                <label>Nama</label>
                <input type="text" class="form-control" name="nama" />
            </div>
            <div class="form-group">
                <label>Nik</label>
                <input type="text" class="form-control" name="nik" />
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="text" class="form-control" name="email" />
            </div>
            <div class="form-group">
                <label>Nomor Telepon</label>
                <input type="text" class="form-control" name="telp" />
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" name="password" />
            </div>
            <div class="form-group">
                <label for="">Jabatan</label>
                <select name="id_jabatan" id="id_jabatan" required
                    class="form-control ">
                    <option value="">Pilih</option>
                    @foreach ($jabatan as $row)
                    <option value="{{ $row->id }}">{{ ucfirst($row->nama) }}</option>
                    @endforeach
                </select>
                <p class="text-danger">{{ $errors->first('id_jabatan') }}</p>
            </div>
            <button type="submit" class="btn btn-primary">Tambah Data</button>
        </form>
    </div>
</div>
@endsection

resources/views/karyawan/edit.blade.php
@extends ('layouts.main')
@section('layout')
<div class="container-fluid">
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Ubah Karyawan</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br/>
    @endif
  
    <form action="{{ route('karyawan.update',$karyawan->id) }}" method="POST">
        @csrf
        @method('PUT')
   
          <div class="form-group">
                <label>Nama</label>
                <input type="text" class="form-control" name="nama" value="{{ $karyawan->nama }}" />
            </div>
            <div class="form-group">
                <label>Nik</label>
                <input type="text" class="form-control" name="nik" value="{{ $karyawan->nik }}"/>
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="text" class="form-control" name="email" value="{{ $user->email }}" />
            </div>
            <div class="form-group">
                <label>Nomor Telepon</label>
                <input type="text" class="form-control" name="telp" value="{{ $karyawan->telp }}" />
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" class="form-control" name="password" value=""/>
            </div>
            <div class="form-group">
                <label for="">Jabatan</label>
                <select name="id_jabatan" id="id_jabatan" required
                    class="form-control ">
                    <option value="">Pilih</option>
                    @foreach ($jabatan as $row)
                    <option value="{{ $row->id }}">{{ ucfirst($row->nama) }}</option>
                    @endforeach
                </select>
                <p class="text-danger">{{ $errors->first('id_jabatan') }}</p>
            </div>
            <button type="submit" class="btn btn-primary">Edit Data</button>
        </div>
   
    </form>
  </div>
</div>
@endsection

resources/views/karyawan/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Presensi</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('/assets/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{('/assets/css/metisMenu.min.css')}}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{{asset('/assets/css/dataTables/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{asset('/assets/css/dataTables/dataTables.responsive.css')}}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{asset('/assets/css/startmin.css')}}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{asset('/assets/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>

<body>
    @extends('layouts.main')
    @section('layout')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Tables</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{{ route('karyawan.create')}}" type="button" class="btn btn-primary">Tambah Karyawan</a>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nik</th>
                                        <th>Nama</th>
                                        <th>No Telepon</th>
                                        <th>Jabatan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $no = 0;?>
                                    @foreach($dk as $dk)
                                    <?php $no++ ;?>
                                    <tr>
                                        <td class="text-center">{{$no}}</td>
                                        <td>{{$dk->nik}}</td>
                                        <td>{{$dk->nama}}</td>
                                        <td>{{$dk->telp}}</td>
                                        <td>{{$dk->nama_jabatan}}</td>
                                        <td>
                                            <form action="{{ route('karyawan.destroy', $dk->id)}}" method="POST">
                                                @csrf
                                                <input type="hidden" name="_method" value="DELETE">
                                                <a href="{{ route('karyawan.edit', $dk->id)}}"
                                                    class="btn btn-warning btn-sm">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->


    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{{asset('/assets/js/jquery.min.js')}}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{asset('/assets/js/bootstrap.min.js')}}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{asset('/assets/js/metisMenu.min.js')}}"></script>

    <!-- DataTables JavaScript -->
    <script src="{{asset('/assets/js/dataTables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('/assets/js/dataTables/dataTables.bootstrap.min.js')}}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{asset('/assets/js/startmin.js')}}"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });

    </script>

    @endsection

</body>

</html>