routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', function () {

	return view('auth.login');
});

Route::group(['middleware' => 'admin'], function() {

	Route::get('/home', function () {
		$data = App\karyawan::count();
		$jml_absensi = App\absen::count();
		$jml_lembur = App\laporanlembur::count();
		$jml_lokasi = App\lokasi::count();
		return view('home', compact('data','jml_absensi','jml_lembur','jml_lokasi'));
	});

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('admin/routes', 'HomeController@admin');
Route::resource('karyawan','KaryawanController');
Route::resource('jabatan','jabatancontroller');
Route::resource('lokasi','lokasicontroller');

Route::get('laporanabsensi', 'laporanabsensicontroller@index');
Route::post('laporanabsensi/search', 'laporanabsensicontroller@search')->name('report.search');
Route::get('laporanlembur', 'laporanlemburcontroller@index');
Route::post('laporanlembur/search', 'laporanlemburcontroller@search')->name('lamporanlembur.search');
});

app/lokasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class lokasi extends Model
{
    protected $table = 'lokasi';

    /**
     * @var array
     */
    protected $guarded = [];
}

app/Http/Controllers/lokasicontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\lokasi;

class lokasicontroller extends Controller
{
    //
    public function index()
    {
        $lokasi = lokasi::all();
        return view('lokasi.index', compact('lokasi'));
    }

    public function create()
    {
        return view('lokasi.create');
    }

  
    public function store(Request $request)
    {
        $validasi = $request->validate([
            'nama' => 'required',
            'lat'=> 'required',
            'long' => 'required',
        ]);
        $lokasi = lokasi::create($validasi);
   
        return redirect('/lokasi')->with('success', 'Selamat data berhasil ditambah!');
    }

    public function edit(lokasi $lokasi)
    {
        return view('lokasi.edit', compact('lokasi'));
    }

    public function update(Request $request, $id)
    {
        $validasi = $request->validate([
            'nama' => 'required',
            'lat'=> 'required',
            'long' => 'required',
        ]);
        lokasi::whereId($id)->update($validasi);

        return redirect('/lokasi')->with('success', 'Data berhasil di update');
    }

    public function destroy($id)
    {
        $lokasi = lokasi::findOrFail($id);
        $lokasi->delete();

        return redirect('/lokasi')->with('success', 'Data berhasil dihapus!');
    }
}

resources/views/lokasi/create.blade.php
@extends ('layouts.main')

@section('layout')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Tambah Lokasi</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('lokasi.store') }}">
            @csrf
            <div class="form-group">
                <label>Nama</label>
                <input type="text" class="form-control" name="nama" />
            </div>
            <div class="form-group">
                <label>Latitude</label>
                <input type="text" class="form-control" name="lat" />
            </div>
            <div class="form-group">
                <label>Longitude</label>
                <input type="text" class="form-control" name="long" />
            </div>
            <button type="submit" class="btn btn-primary">Tambah Data</button>
        </form>
    </div>
</div>
@endsection

resources/views/lokasi/edit.blade.php
@extends ('layouts.main')
@section('layout')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Ubah Lokasi</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br/>
    @endif
  
    <form action="{{ route('lokasi.update',$lokasi->id) }}" method="POST">
        @csrf
        @method('PUT')
   
            <div class="form-group"> 
              <label>Nama</label>
              <input type="text" class="form-control" name="nama" value="{{ $lokasi->nama }}"/>
          </div>
            <div class="form-group"> 
              <label>Latitude</label>
              <input type="text" class="form-control" name="lat" value="{{ $lokasi->lat }}"/>
          </div>
            <div class="form-group"> 
              <label>Longitude</label>
              <input type="text" class="form-control" name="long" value="{{ $lokasi->long }}"/>
          </div>
            <button type="submit" class="btn btn-primary">Edit Data</button>
        </div>
   
    </form>
  </div>
</div>
@endsection

resources/views/lokasi/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Presensi</title>

   </head>

<body>
    @extends('layouts.main')
    @section('layout')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Daftar Lokasi</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{{ route('lokasi.create')}}" type="button" class="btn btn-primary">Tambah Lokasi</a>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Latitude</th>
                                        <th>Longitude</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $no = 0;?>
                                    @foreach($lokasi as $data)
                                    <?php $no++ ;?>
                                    <tr>
                                        <td class="text-center">{{$no}}</td>
                                        <td>{{$data->nama}}</td>
                                        <td>{{$data->lat}}</td>
                                        <td>{{$data->long}}</td>
                                        <td>
                                            <form action="{{ route('lokasi.destroy', $data->id)}}" method="POST">
                                                @csrf
                                                <input type="hidden" name="_method" value="DELETE">
                                                <a href="{{ route('lokasi.edit', $data->id)}}"
                                                    class="btn btn-warning btn-sm">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

    @endsection

</body>

</html>